# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'DigitalDesigns' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DigitalDesigns
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
